### ISSUE TITLE
Add a link to be dragged to the bookmark bar

### ISSUE THREAD

**Issue by zhouzi** [tomhodgins/dragon#5]
Setting up the bookmarklet is not that easy and might stop some people from using it. It'd be great to add a link to be dragged to the top bar. Right now, the dragon.js file is not hosted on a https site so it wouldn't work on sites that use an ssl certificate.

To solve that, the demo could be moved to a github page which uses https. Then you'd just have to include a link with:

```
javascript:(function()%7Bvar script%3Ddocument.createElement(%27script%27)%3Bscript.setAttribute(%27src%27, %27https://path/to/dragon.js%27)%3Bdocument.body.appendChild(script)%3B%7D())%3B
```

**Comment by tomhodgins** [comment]
Hi Zhouzi.

**Re HTTPS:**

The fact that the Dragon demo page is not hosted on HTTPS shouldn't be an issue, when you're using the `dragon.js` code as a bookmarklet, 100% of the code of the bookmarklet is stored within your browser so it can be loaded into whatever page you have loaded, whether that page was retrieved via HTTP or HTTPS. It doesn't actually access any code from the network when it runs :)

**Re: homepage + link**

In my mind, this is a one-line file that I had saved as a [Gist](https://gist.github.com/tomhodgins/f8a6140f8e06b868db13) (which _is_ version-controlled and publically accessible but not very visible) and so creating an entire github project for it I viewed as making a big homepage for that little bit of code already.

I do think eventually hosting the demo page and more information on Github itself might be a good idea - if the branch is switched to `gh-pages` and there's an index.html in the repository we would we able to access the test right from Github, as well as have a page where people could drag the link into their address bar.

The reason I have not done this is that Github pages does not yet support HTTPS, and a lack of time :) I've been busy building some new things! 

As a method for installing bookmarklets, dragging a link doesn't help you at all in the browsers where adding a bookmarklet needs the most assistance: Mobile Safari (iOS). In the browsers I wrote this too to use, dragging links to an address bar isn't a feature of that browser. Also, many browsers will refuse to display a link to JavaScript (instead of a URL) as a link, meaning that if the purpose of putting a 'draggable link' on the page is to make it easy - if for any reason it doesn't work that's harder to troubleshoot than following the directions of creating a bookmark manually that you can repeat until you get it right.

Here's a link to the JS of Dragon right here, but I'm not sure what I could/would do with this in most of the browsers where I want to use it:

<a href="javascript:/*dragon*/var%20b%3DX%3DY%3DT%3DL%3D0%3Bdocument.addEventListener%28%22click%22%2Cfunction%28a%29%7Ba.preventDefault%28%29%7D%2C%210%29%3Bdocument.addEventListener%28%22mousedown%22%2Cc%29%3Bdocument.addEventListener%28%22touchstart%22%2Cc%29%3Bfunction%20c%28a%29%7Ba.preventDefault%28%29%3Ba.target%21%3D%3Ddocument.documentElement%26%26a.target%21%3D%3Ddocument.body%26%26%28b%3DDate.now%28%29%2Ca.target.setAttribute%28%22data-drag%22%2Cb%29%2Ca.target.style.position%3D%22relative%22%2CT%3Da.target.style.top.split%28%22px%22%29%5B0%5D%7C%7C0%2CL%3Da.target.style.left.split%28%22px%22%29%5B0%5D%7C%7C0%29%3BX%3Da.clientX%7C%7Ca.touches%5B0%5D.clientX%3BY%3Da.clientY%7C%7Ca.touches%5B0%5D.clientY%7Ddocument.addEventListener%28%22mousemove%22%2Cd%29%3Bdocument.addEventListener%28%22touchmove%22%2Cd%29%3Bfunction%20d%28a%29%7Bif%28%22%22%21%3D%3Db%29%7Bvar%20e%3Ddocument.querySelector%28%27%5Bdata-drag%3D%22%27+b+%27%22%5D%27%29%3Be.style.top%3DparseInt%28T%29+parseInt%28%28a.clientY%7C%7Ca.touches%5B0%5D.clientY%29-Y%29+%22px%22%3Be.style.left%3DparseInt%28L%29+parseInt%28%28a.clientX%7C%7Ca.touches%5B0%5D.clientX%29-X%29+%22px%22%7D%7Ddocument.addEventListener%28%22mouseup%22%2Cf%29%3Bdocument.addEventListener%28%22touchend%22%2Cf%29%3Bfunction%20f%28%29%7Bb%3D%22%22%7Ddocument.addEventListener%28%22mouseover%22%2Cg%29%3Bfunction%20g%28a%29%7Ba.target.style.cursor%3D%22move%22%3Ba.target.style.boxShadow%3D%22inset%20lime%200%200%201px%2Clime%200%200%201px%22%7Ddocument.addEventListener%28%22mouseout%22%2Ch%29%3Bfunction%20h%28a%29%7Ba.target.style.cursor%3Da.target.style.boxShadow%3D%22%22%7D%3B">Bookmark Dragon.js</a>

In some, it may not show up as a clickable link simply because the URL isn't to another page.

**Comment by zhouzi** [comment]
My bad, I've been a bit unclear so in case my point was confusing, here is what I meant. There are two ways to create a bookmarklet:
1. Add a bookmark and paste the whole library's code, starting with `javascript:`
   - No http/https issues
   - The library code is not updated when changes are made
2. Add a bookmark that creates and insert a script element pointing to the script
   - Must be hosted on an https source
   - The library code is automatically updated

But if I've suggested to add a draggable link it is mostly because to give a try to dragon.js I had to find the source code, copy it, add a bookmark and paste the code. While with such link I would have to just drag it to the bookmark bar ^^

Anyway, once again I get your points and the fact that you just want to have fun building things quickly :)
